# 📊 01 - Data Collection and Loading
## Product Price Prediction Project
**Week 1 | Unit I**

### Dataset Columns:
- uniq_id, crawl_timestamp, product_url, product_name
- product_category_tree, pid, retail_price, discounted_price
- images, description, product_rating, overall_rating
- brand, product_specifications

---

In [32]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import os

# Settings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 50)
pd.set_option('display.float_format', '{:.2f}'.format)

print("✅ Libraries imported successfully!")
print(f"📦 Pandas version: {pd.__version__}")
print(f"📦 NumPy version: {np.__version__}")

✅ Libraries imported successfully!
📦 Pandas version: 2.3.3
📦 NumPy version: 2.2.4

In [33]:

# Load your dataset (change filename if needed)
df = pd.read_csv("flipkart_com_ecommerce_sample.csv")

# OR if file is in same folder as notebook:
# df = pd.read_csv('product_data.csv')

print("=" * 60)
print("✅ DATASET LOADED SUCCESSFULLY!")
print("=" * 60)
print(f"📊 Total Rows: {df.shape[0]:,}")
print(f"📊 Total Columns: {df.shape[1]}")

============================================================
✅ DATASET LOADED SUCCESSFULLY!
============================================================
📊 Total Rows: 20,002
📊 Total Columns: 291

In [34]:
# ====================================
# VIEW ALL COLUMN NAMES
# ====================================
print("=" * 60)
print("ALL COLUMNS IN DATASET")
print("=" * 60)

for i, col in enumerate(df.columns, 1):
    print(f"{i:2}. {col}")

============================================================
ALL COLUMNS IN DATASET
============================================================
 1. uniq_id
 2. crawl_timestamp
 3. product_url
 4. product_name
 5. product_category_tree
 6. pid
 7. retail_price
 8. discounted_price
 9. image
10. is_FK_Advantage_product
11. description
12. product_rating
13. overall_rating
14. brand
15. product_specifications
16. price_2025-05-01
17. price_2025-05-02
18. price_2025-05-03
19. price_2025-05-04
20. price_2025-05-05
21. price_2025-05-06
22. price_2025-05-07
23. price_2025-05-08
24. price_2025-05-09
25. price_2025-05-10
26. price_2025-05-11
27. price_2025-05-12
28. price_2025-05-13
29. price_2025-05-14
30. price_2025-05-15
31. price_2025-05-16
32. price_2025-05-17
33. price_2025-05-18
34. price_2025-05-19
35. price_2025-05-20
36. price_2025-05-21
37. price_2025-05-22
38. price_2025-05-23
39. price_2025-05-24
40. price_2025-05-25
41. price_2025-05-26
42. price_2025-05-27
43. price_2025-05-28
44. price_2025-05-29
45. price_2025-05-30
46. price_2025-05-31
47. price_2025-06-01
48. price_2025-06-02
49. price_2025-06-03
50. price_2025-06-04
51. price_2025-06-05
52. price_2025-06-06
53. price_2025-06-07
54. price_2025-06-08
55. price_2025-06-09
56. price_2025-06-10
57. price_2025-06-11
58. price_2025-06-12
59. price_2025-06-13
60. price_2025-06-14
61. price_2025-06-15
62. price_2025-06-16
63. price_2025-06-17
64. price_2025-06-18
65. price_2025-06-19
66. price_2025-06-20
67. price_2025-06-21
68. price_2025-06-22
69. price_2025-06-23
70. price_2025-06-24
71. price_2025-06-25
72. price_2025-06-26
73. price_2025-06-27
74. price_2025-06-28
75. price_2025-06-29
76. price_2025-06-30
77. price_2025-07-01
78. price_2025-07-02
79. price_2025-07-03
80. price_2025-07-04
81. price_2025-07-05
82. price_2025-07-06
83. price_2025-07-07
84. price_2025-07-08
85. price_2025-07-09
86. price_2025-07-10
87. price_2025-07-11
88. price_2025-07-12
89. price_2025-07-13
90. price_2025-07-14
91. price_2025-07-15
92. price_2025-07-16
93. price_2025-07-17
94. price_2025-07-18
95. price_2025-07-19
96. price_2025-07-20
97. price_2025-07-21
98. price_2025-07-22
99. price_2025-07-23
100. price_2025-07-24
101. price_2025-07-25
102. price_2025-07-26
103. price_2025-07-27
104. price_2025-07-28
105. price_2025-07-29
106. price_2025-07-30
107. price_2025-07-31
108. price_2025-08-01
109. price_2025-08-02
110. price_2025-08-03
111. price_2025-08-04
112. price_2025-08-05
113. price_2025-08-06
114. price_2025-08-07
115. price_2025-08-08
116. price_2025-08-09
117. price_2025-08-10
118. price_2025-08-11
119. price_2025-08-12
120. price_2025-08-13
121. price_2025-08-14
122. price_2025-08-15
123. price_2025-08-16
124. price_2025-08-17
125. price_2025-08-18
126. price_2025-08-19
127. price_2025-08-20
128. price_2025-08-21
129. price_2025-08-22
130. price_2025-08-23
131. price_2025-08-24
132. price_2025-08-25
133. price_2025-08-26
134. price_2025-08-27
135. price_2025-08-28
136. price_2025-08-29
137. price_2025-08-30
138. price_2025-08-31
139. price_2025-09-01
140. price_2025-09-02
141. price_2025-09-03
142. price_2025-09-04
143. price_2025-09-05
144. price_2025-09-06
145. price_2025-09-07
146. price_2025-09-08
147. price_2025-09-09
148. price_2025-09-10
149. price_2025-09-11
150. price_2025-09-12
151. price_2025-09-13
152. price_2025-09-14
153. price_2025-09-15
154. price_2025-09-16
155. price_2025-09-17
156. price_2025-09-18
157. price_2025-09-19
158. price_2025-09-20
159. price_2025-09-21
160. price_2025-09-22
161. price_2025-09-23
162. price_2025-09-24
163. price_2025-09-25
164. price_2025-09-26
165. price_2025-09-27
166. price_2025-09-28
167. price_2025-09-29
168. price_2025-09-30
169. price_2025-10-01
170. price_2025-10-02
171. price_2025-10-03
172. price_2025-10-04
173. price_2025-10-05
174. price_2025-10-06
175. price_2025-10-07
176. price_2025-10-08
177. price_2025-10-09
178. price_2025-10-10
179. price_2025-10-11
180. price_2025-10-12
181. price_2025-10-13
182. price_2025-10-14
183. price_2025-10-15
184. price_2025-10-16
185. price_2025-10-17
186. price_2025-10-18
187. price_2025-10-19
188. price_2025-10-20
189. price_2025-10-21
190. price_2025-10-22
191. price_2025-10-23
192. price_2025-10-24
193. price_2025-10-25
194. price_2025-10-26
195. price_2025-10-27
196. price_2025-10-28
197. price_2025-10-29
198. price_2025-10-30
199. price_2025-10-31
200. price_2025-11-01
201. price_2025-11-02
202. price_2025-11-03
203. price_2025-11-04
204. price_2025-11-05
205. price_2025-11-06
206. price_2025-11-07
207. price_2025-11-08
208. price_2025-11-09
209. price_2025-11-10
210. price_2025-11-11
211. price_2025-11-12
212. price_2025-11-13
213. price_2025-11-14
214. price_2025-11-15
215. price_2025-11-16
216. price_2025-11-17
217. price_2025-11-18
218. price_2025-11-19
219. price_2025-11-20
220. price_2025-11-21
221. price_2025-11-22
222. price_2025-11-23
223. price_2025-11-24
224. price_2025-11-25
225. price_2025-11-26
226. price_2025-11-27
227. price_2025-11-28
228. price_2025-11-29
229. price_2025-11-30
230. price_2025-12-01
231. price_2025-12-02
232. price_2025-12-03
233. price_2025-12-04
234. price_2025-12-05
235. price_2025-12-06
236. price_2025-12-07
237. price_2025-12-08
238. price_2025-12-09
239. price_2025-12-10
240. price_2025-12-11
241. price_2025-12-12
242. price_2025-12-13
243. price_2025-12-14
244. price_2025-12-15
245. price_2025-12-16
246. price_2025-12-17
247. price_2025-12-18
248. price_2025-12-19
249. price_2025-12-20
250. price_2025-12-21
251. price_2025-12-22
252. price_2025-12-23
253. price_2025-12-24
254. price_2025-12-25
255. price_2025-12-26
256. price_2025-12-27
257. price_2025-12-28
258. price_2025-12-29
259. price_2025-12-30
260. price_2025-12-31
261. price_2026-01-01
262. price_2026-01-02
263. price_2026-01-03
264. price_2026-01-04
265. price_2026-01-05
266. price_2026-01-06
267. price_2026-01-07
268. price_2026-01-08
269. price_2026-01-09
270. price_2026-01-10
271. price_2026-01-11
272. price_2026-01-12
273. price_2026-01-13
274. price_2026-01-14
275. price_2026-01-15
276. price_2026-01-16
277. price_2026-01-17
278. price_2026-01-18
279. price_2026-01-19
280. price_2026-01-20
281. price_2026-01-21
282. price_2026-01-22
283. price_2026-01-23
284. price_2026-01-24
285. price_2026-01-25
286. price_2026-01-26
287. price_2026-01-27
288. price_2026-01-28
289. price_2026-01-29
290. price_2026-01-30
291. price_2026-01-31

In [35]:
# ====================================
# VIEW FIRST 5 ROWS
# ====================================
print("=" * 60)
print("FIRST 5 ROWS")
print("=" * 60)
df.head()

============================================================
FIRST 5 ROWS
============================================================

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications,price_2025-05-01,price_2025-05-02,price_2025-05-03,price_2025-05-04,price_2025-05-05,price_2025-05-06,price_2025-05-07,price_2025-05-08,price_2025-05-09,price_2025-05-10,price_2025-05-11,price_2025-05-12,price_2025-05-13,price_2025-05-14,price_2025-05-15,price_2025-05-16,price_2025-05-17,price_2025-05-18,price_2025-05-19,price_2025-05-20,price_2025-05-21,price_2025-05-22,price_2025-05-23,price_2025-05-24,price_2025-05-25,price_2025-05-26,price_2025-05-27,price_2025-05-28,price_2025-05-29,price_2025-05-30,price_2025-05-31,price_2025-06-01,price_2025-06-02,price_2025-06-03,price_2025-06-04,price_2025-06-05,price_2025-06-06,price_2025-06-07,price_2025-06-08,price_2025-06-09,price_2025-06-10,price_2025-06-11,price_2025-06-12,price_2025-06-13,price_2025-06-14,price_2025-06-15,price_2025-06-16,price_2025-06-17,price_2025-06-18,price_2025-06-19,price_2025-06-20,price_2025-06-21,price_2025-06-22,price_2025-06-23,price_2025-06-24,price_2025-06-25,price_2025-06-26,price_2025-06-27,price_2025-06-28,price_2025-06-29,price_2025-06-30,price_2025-07-01,price_2025-07-02,price_2025-07-03,price_2025-07-04,price_2025-07-05,price_2025-07-06,price_2025-07-07,price_2025-07-08,price_2025-07-09,price_2025-07-10,price_2025-07-11,price_2025-07-12,price_2025-07-13,price_2025-07-14,price_2025-07-15,price_2025-07-16,price_2025-07-17,price_2025-07-18,price_2025-07-19,price_2025-07-20,price_2025-07-21,price_2025-07-22,price_2025-07-23,price_2025-07-24,price_2025-07-25,price_2025-07-26,price_2025-07-27,price_2025-07-28,price_2025-07-29,price_2025-07-30,price_2025-07-31,price_2025-08-01,price_2025-08-02,price_2025-08-03,price_2025-08-04,price_2025-08-05,price_2025-08-06,price_2025-08-07,price_2025-08-08,price_2025-08-09,price_2025-08-10,price_2025-08-11,price_2025-08-12,price_2025-08-13,price_2025-08-14,price_2025-08-15,price_2025-08-16,price_2025-08-17,price_2025-08-18,price_2025-08-19,price_2025-08-20,price_2025-08-21,price_2025-08-22,price_2025-08-23,price_2025-08-24,price_2025-08-25,price_2025-08-26,price_2025-08-27,price_2025-08-28,price_2025-08-29,price_2025-08-30,price_2025-08-31,price_2025-09-01,price_2025-09-02,price_2025-09-03,price_2025-09-04,price_2025-09-05,price_2025-09-06,price_2025-09-07,price_2025-09-08,price_2025-09-09,price_2025-09-10,price_2025-09-11,price_2025-09-12,price_2025-09-13,price_2025-09-14,price_2025-09-15,price_2025-09-16,price_2025-09-17,price_2025-09-18,price_2025-09-19,price_2025-09-20,price_2025-09-21,price_2025-09-22,price_2025-09-23,price_2025-09-24,price_2025-09-25,price_2025-09-26,price_2025-09-27,price_2025-09-28,price_2025-09-29,price_2025-09-30,price_2025-10-01,price_2025-10-02,price_2025-10-03,price_2025-10-04,price_2025-10-05,price_2025-10-06,price_2025-10-07,price_2025-10-08,price_2025-10-09,price_2025-10-10,price_2025-10-11,price_2025-10-12,price_2025-10-13,price_2025-10-14,price_2025-10-15,price_2025-10-16,price_2025-10-17,price_2025-10-18,price_2025-10-19,price_2025-10-20,price_2025-10-21,price_2025-10-22,price_2025-10-23,price_2025-10-24,price_2025-10-25,price_2025-10-26,price_2025-10-27,price_2025-10-28,price_2025-10-29,price_2025-10-30,price_2025-10-31,price_2025-11-01,price_2025-11-02,price_2025-11-03,price_2025-11-04,price_2025-11-05,price_2025-11-06,price_2025-11-07,price_2025-11-08,price_2025-11-09,price_2025-11-10,price_2025-11-11,price_2025-11-12,price_2025-11-13,price_2025-11-14,price_2025-11-15,price_2025-11-16,price_2025-11-17,price_2025-11-18,price_2025-11-19,price_2025-11-20,price_2025-11-21,price_2025-11-22,price_2025-11-23,price_2025-11-24,price_2025-11-25,price_2025-11-26,price_2025-11-27,price_2025-11-28,price_2025-11-29,price_2025-11-30,price_2025-12-01,price_2025-12-02,price_2025-12-03,price_2025-12-04,price_2025-12-05,price_2025-12-06,price_2025-12-07,price_2025-12-08,price_2025-12-09,price_2025-12-10,price_2025-12-11,price_2025-12-12,price_2025-12-13,price_2025-12-14,price_2025-12-15,price_2025-12-16,price_2025-12-17,price_2025-12-18,price_2025-12-19,price_2025-12-20,price_2025-12-21,price_2025-12-22,price_2025-12-23,price_2025-12-24,price_2025-12-25,price_2025-12-26,price_2025-12-27,price_2025-12-28,price_2025-12-29,price_2025-12-30,price_2025-12-31,price_2026-01-01,price_2026-01-02,price_2026-01-03,price_2026-01-04,price_2026-01-05,price_2026-01-06,price_2026-01-07,price_2026-01-08,price_2026-01-09,price_2026-01-10,price_2026-01-11,price_2026-01-12,price_2026-01-13,price_2026-01-14,price_2026-01-15,price_2026-01-16,price_2026-01-17,price_2026-01-18,price_2026-01-19,price_2026-01-20,price_2026-01-21,price_2026-01-22,price_2026-01-23,price_2026-01-24,price_2026-01-25,price_2026-01-26,price_2026-01-27,price_2026-01-28,price_2026-01-29,price_2026-01-30,price_2026-01-31
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.00,379.00,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ...",410.00,405.00,417.00,434.00,395.00,395.00,431.00,419.00,390.00,422.00,394.00,390.00,412.00,361.00,365.00,388.00,383.00,410.00,381.00,380.00,429.00,395.00,401.00,375.00,393.00,402.00,380.00,411.00,388.00,394.00,391.00,441.00,399.00,378.00,416.00,375.00,404.00,364.00,377.00,404.00,414.00,410.00,397.00,394.00,378.00,389.00,394.00,421.00,406.00,364.00,406.00,396.00,390.00,412.00,420.00,418.00,383.00,393.00,410.00,423.00,390.00,396.00,377.00,376.00,416.00,431.00,402.00,427.00,407.00,387.00,407.00,430.00,403.00,435.00,355.00,416.00,401.00,394.00,401.00,363.00,399.00,407.00,429.00,389.00,383.00,390.00,422.00,410.00,393.00,417.00,404.00,419.00,386.00,397.00,401.00,370.00,406.00,405.00,400.00,395.00,383.00,395.00,393.00,384.00,307.00,287.00,351.00,299.00,299.00,379.00,361.00,399.00,401.00,449.00,400.00,410.00,399.00,376.00,422.00,415.00,415.00,385.00,432.00,372.00,421.00,443.00,388.00,388.00,406.00,393.00,369.00,407.00,378.00,409.00,385.00,435.00,393.00,393.00,416.00,377.00,404.00,426.00,371.00,407.00,405.00,415.00,375.00,373.00,410.00,330.00,253.00,254.00,241.00,253.00,253.00,241.00,273.00,256.00,293.00,323.00,385.00,415.00,335.00,255.00,262.00,305.00,298.00,324.00,314.00,310.00,270.00,350.00,270.00,254.00,253.00,260.00,250.00,268.00,246.00,284.00,364.00,382.00,378.00,413.00,399.00,418.00,409.00,398.00,383.00,369.00,391.00,421.00,408.00,375.00,403.00,407.00,382.00,409.00,405.00,381.00,407.00,411.00,421.00,421.00,372.00,385.00,414.00,416.00,410.00,477.00,411.00,331.00,262.00,258.00,246.00,259.00,339.00,395.00,390.00,405.00,450.00,370.00,413.00,367.00,396.00,421.00,405.00,382.00,306.00,266.00,311.00,319.00,285.00,269.00,349.00,304.00,224.00,288.00,251.00,269.00,349.00,269.00,258.00,261.00,267.00,246.00,274.00,256.00,336.00,408.00,374.00,418.00,448.00,420.00,373.00,394.00,430.00,385.00,408.00,415.00,381.00,402.00,338.00,379.00,299.00,234.00,270.00,232.00,244.00,280.00,268.00,348.00,423.00,400.00,381.00,415.00
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.00,22646.00,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,No rating available,No rating available,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati...",23500.00,22270.00,23350.00,22490.00,22280.00,23530.00,23100.00,22530.00,23640.00,21220.00,22130.00,23710.00,22920.00,22790.00,23510.00,21900.00,22340.00,23730.00,22340.00,22230.00,23200.00,23740.00,23850.00,22400.00,21720.00,22310.00,22330.00,22760.00,23320.00,23420.00,23840.00,21830.00,22320.00,21860.00,21780.00,23720.00,23510.00,24030.00,22910.00,21910.00,23140.00,22270.00,23460.00,21760.00,22200.00,22210.00,21690.00,22830.00,23090.00,21650.00,23500.00,22380.00,22560.00,22220.00,22040.00,22680.00,22130.00,23090.00,22580.00,22110.00,22800.00,21890.00,22910.00,22760.00,21710.00,23520.00,23920.00,23000.00,22760.00,22040.00,21120.00,22420.00,22270.00,22970.00,21850.00,23240.00,22170.00,23310.00,21730.00,23030.00,21960.00,22970.00,23550.00,22400.00,22440.00,23710.00,22620.00,23030.00,23180.00,22320.00,23220.00,22250.00,23650.00,21700.00,22810.00,22440.00,22820.00,22740.00,23890.00,23120.00,22950.00,23290.00,24010.00,21620.00,19050.00,20070.00,19430.00,19840.00,19760.00,22330.00,23520.00,23660.00,22210.00,22050.00,21690.00,22870.00,22420.00,23380.00,24170.00,22840.00,22000.00,23330.00,22520.00,23280.00,22030.00,22920.00,22700.00,21890.00,22090.00,23810.00,22950.00,22550.00,22440.00,23200.00,22350.00,21880.00,21840.00,23770.00,23380.00,23210.00,23860.00,22750.00,22710.00,23740.00,23750.00,23180.00,23120.00,22700.00,22950.00,20380.00,17810.00,18850.00,16280.00,14390.00,16960.00,15900.00,17680.00,15110.00,17680.00,20250.00,22820.00,21370.00,18800.00,18280.00,18770.00,17840.00,18020.00,19480.00,19090.00,20320.00,20030.00,22430.00,19860.00,17290.00,14720.00,14510.00,15230.00,16740.00,16450.00,14510.00,17080.00,19650.00,22150.00,22530.00,24630.00,23310.00,22760.00,23090.00,22520.00,23240.00,23450.00,22840.00,22230.00,23220.00,22700.00,21520.00,22120.00,23850.00,23790.00,21970.00,22740.00,22410.00,23310.00,22630.00,22820.00,23380.00,22420.00,22250.00,21630.00,21150.00,22510.00,19940.00,18270.00,17800.00,19520.00,20110.00,22680.00,23150.00,23660.00,22770.00,22580.00,23200.00,22310.00,22720.00,22830.00,24460.00,22430.00,23000.00,20700.00,19300.00,20470.00,19580.00,20940.00,19790.00,22360.00,19790.00,18310.00,18970.00,18210.00,18500.00,21070.00,19580.00,20210.00,18780.00,16450.00,19020.00,17900.00,17920.00,20490.00,21360.00,21070.00,23250.00,23690.00,22890.00,23900.00,21790.00,22490.00,22630.00,21970.00,22150.00,22890.00,22490.00,22840.00,23120.00,20550.00,17980.00,19280.00,19910.00,17520.00,16980.00,16540.00,19110.00,21680.00,23180.00,22320.00,22550.00
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.00,499.00,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,Key Features of AW Bellies Sandals Wedges Heel...,No rating available,No rating available,AW,"{""product_specification""=>[{""key""=>""Ideal For""...",547.00,488.00,489.00,490.00,512.00,462.00,490.00,500.00,509.00,554.00,521.00,502.00,501.00,472.00,480.00,452.00,459.00,477.00,487.00,537.00,491.00,467.00,530.00,450.00,506.00,515.00,473.00,507.00,520.00,470.00,496.00,576.00,496.00,519.00,492.00,476.00,523.00,514.00,484.00,508.00,526.00,488.00,530.00,466.00,487.00,497.00,519.00,479.00,540.00,468.00,517.00,515.00,501.00,527.00,484.00,457.00,486.00,547.00,505.00,515.00,500.00,478.00,546.00,506.00,486.00,529.00,501.00,517.00,498.00,532.00,556.00,550.00,534.00,478.00,497.00,513.00,501.00,507.00,439.00,519.00,514.00,514.00,496.00,481.00,535.00,530.00,476.00,491.00,464.00,529.00,482.00,490.00,472.00,499.00,429.00,493.00,496.00,517.00,556.00,550.00,472.00,483.00,529.00,506.00,444.00,402.00,449.00,435.00,398.00,478.00,469.00,511.00,469.00,495.00,481.00,552.00,472.00,524.00,527.00,447.00,463.00,508.00,469.00,477.00,463.00,505.00,536.00,543.00,509.00,501.00,508.00,535.00,503.00,516.00,489.00,509.00,535.00,495.00,480.00,525.00,467.00,485.00,498.00,490.00,496.00,449.00,522.00,493.00,480.00,400.00,320.00,343.00,328.00,336.00,256.00,309.00,303.00,380.00,401.00,395.00,462.00,507.00,427.00,436.00,423.00,394.00,394.00,436.00,450.00,374.00,385.00,465.00,385.00,305.00,250.00,313.00,336.00,256.00,281.00,242.00,322.00,402.00,482.00,500.00,510.00,550.00,542.00,530.00,453.00,453.00,496.00,493.00,528.00,459.00,484.00,481.00,489.00,481.00,496.00,450.00,485.00,519.00,452.00,532.00,506.00,513.00,505.00,521.00,472.00,494.00,533.00,453.00,373.00,298.00,378.00,379.00,459.00,505.00,506.00,508.00,538.00,515.00,508.00,491.00,456.00,470.00,505.00,540.00,460.00,390.00,401.00,421.00,438.00,403.00,483.00,413.00,382.00,369.00,361.00,389.00,469.00,389.00,379.00,360.00,382.00,340.00,374.00,343.00,423.00,501.00,496.00,460.00,491.00,514.00,506.00,504.00,521.00,479.00,498.00,501.00,548.00,496.00,520.00,484.00,404.00,409.00,329.00,343.00,311.00,381.00,363.00,443.00,462.00,528.00,560.00,493.00
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.00,267.00,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ...",274.00,276.00,263.00,269.00,266.00,269.00,279.00,283.00,301.00,270.00,296.00,277.00,279.00,289.00,264.00,285.00,285.00,289.00,284.00,314.00,271.00,272.00,271.00,281.00,279.00,296.00,299.00,272.00,268.00,286.00,279.00,291.00,282.00,258.00,301.00,305.00,277.00,277.00,286.00,284.00,291.00,308.00,277.00,268.00,264.00,277.00,279.00,305.00,272.00,283.00,282.00,299.00,318.00,272.00,281.00,294.00,289.00,305.00,292.00,277.00,288.00,295.00,291.00,287.00,295.00,299.00,302.00,289.00,277.00,282.00,296.00,268.00,288.00,277.00,280.00,297.00,282.00,280.00,261.00,293.00,298.00,310.00,275.00,283.00,283.00,302.00,281.00,286.00,288.00,282.00,273.00,282.00,295.00,268.00,284.00,270.00,296.00,258.00,272.00,285.00,305.00,286.00,272.00,306.00,250.00,200.00,208.00,177.00,194.00,250.00,283.00,272.00,262.00,292.00,292.00,281.00,305.00,268.00,258.00,272.00,279.00,286.00,279.00,285.00,262.00,300.00,278.00,295.00,295.00,289.00,288.00,286.00,289.00,298.00,282.00,292.00,285.00,300.00,277.00,305.00,279.00,260.00,284.00,278.00,291.00,270.00,273.00,253.00,276.00,220.00,164.00,181.00,182.00,178.00,166.00,174.00,175.00,165.00,196.00,219.00,275.00,282.00,226.00,188.00,187.00,187.00,166.00,222.00,239.00,223.00,193.00,249.00,193.00,183.00,175.00,169.00,181.00,178.00,183.00,180.00,236.00,272.00,298.00,282.00,312.00,280.00,304.00,282.00,273.00,273.00,281.00,288.00,290.00,272.00,279.00,310.00,306.00,286.00,291.00,284.00,291.00,268.00,276.00,257.00,285.00,299.00,283.00,302.00,262.00,259.00,284.00,228.00,189.00,171.00,184.00,181.00,237.00,292.00,293.00,260.00,303.00,306.00,271.00,285.00,287.00,283.00,275.00,279.00,223.00,223.00,201.00,203.00,191.00,196.00,252.00,196.00,207.00,189.00,170.00,197.00,253.00,197.00,177.00,187.00,175.00,194.00,183.00,170.00,226.00,274.00,301.00,291.00,275.00,275.00,278.00,312.00,285.00,290.00,294.00,283.00,276.00,282.00,281.00,285.00,229.00,191.00,197.00,174.00,175.00,157.00,183.00,239.00,294.00,242.00,298.00,280.00
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.00,210.00,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,Specifications of Sicons All Purpose Arnica Do...,No rating available,No rating available,Sicons,"{""product_specification""=>[{""key""=>""Pet Type"",...",214.00,199.00,213.00,199.00,205.00,218.00,208.00,215.00,213.00,218.00,218.00,208.00,218.00,206.00,210.00,212.00,214.00,213.00,210.00,201.00,218.00,209.00,206.00,203.00,215.00,216.00,209.00,215.00,218.00,218.00,206.00,217.00,218.00,207.00,212.00,218.00,205.00,218.00,212.00,213.00,211.00,207.00,200.00,200.00,218.00,213.00,208.00,195.00,204.00,205.00,218.00,218.00,208.00,218.00,213.00,213.00,195.00,213.00,201.00,202.00,214.00,218.00,218.00,212.00,218.00,218.00,218.00,217.00,214.00,212.00,212.00,205.00,205.00,213.00,201.00,203.00,207.00,215.00,218.00,200.00,212.00,218.00,200.00,204.00,212.00,203.00,210.00,205.00,211.00,218.00,202.00,209.00,208.00,211.00,208.00,218.00,206.00,211.00,210.00,213.00,214.00,215.00,208.00,208.00,190.00,201.00,190.00,187.00,180.00,198.00,205.00,213.00,202.00,215.00,211.00,218.00,201.00,208.00,212.00,217.00,205.00,211.00,209.00,206.00,217.00,218.00,206.00,200.00,210.00,218.00,203.00,218.00,218.00,207.00,216.00,218.00,216.00,209.00,209.00,204.00,212.00,198.00,216.00,202.00,207.00,199.00,212.00,216.00,198.00,180.00,162.00,162.00,164.00,163.00,168.00,167.00,180.00,181.00,199.00,181.00,199.00,198.00,185.00,185.00,185.00,193.00,192.00,197.00,191.00,193.00,203.00,214.00,196.00,178.00,160.00,154.00,172.00,173.00,158.00,172.00,190.00,200.00,193.00,208.00,207.00,197.00,215.00,218.00,204.00,213.00,212.00,210.00,212.00,211.00,213.00,208.00,202.00,214.00,207.00,204.00,211.00,204.00,208.00,211.00,218.00,217.00,216.00,218.00,213.00,214.00,214.00,196.00,180.00,168.00,186.00,176.00,194.00,208.00,216.00,217.00,209.00,202.00,206.00,214.00,198.00,210.00,218.00,218.00,200.00,201.00,189.00,193.00,188.00,193.00,206.00,188.00,186.00,188.00,183.00,192.00,210.00,192.00,174.00,177.00,176.00,186.00,179.00,172.00,190.00,208.00,202.00,198.00,210.00,211.00,198.00,213.00,215.00,209.00,206.00,207.00,214.00,214.00,207.00,209.00,191.00,173.00,182.00,187.00,173.00,178.00,195.00,209.00,209.00,210.00,208.00,218.00

In [36]:
# ====================================
# DATASET INFO
# ====================================
print("=" * 60)
print("DATASET INFO")
print("=" * 60)
df.info()

============================================================
DATASET INFO
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20002 entries, 0 to 20001
Columns: 291 entries, uniq_id to price_2026-01-31
dtypes: float64(278), object(13)
memory usage: 44.4+ MB

In [37]:
# ====================================
# STATISTICAL SUMMARY (Numerical Columns)
# ====================================
print("=" * 60)
print("STATISTICAL SUMMARY")
print("=" * 60)
df.describe()

============================================================
STATISTICAL SUMMARY
============================================================

,retail_price,discounted_price,price_2025-05-01,price_2025-05-02,price_2025-05-03,price_2025-05-04,price_2025-05-05,price_2025-05-06,price_2025-05-07,price_2025-05-08,price_2025-05-09,price_2025-05-10,price_2025-05-11,price_2025-05-12,price_2025-05-13,price_2025-05-14,price_2025-05-15,price_2025-05-16,price_2025-05-17,price_2025-05-18,price_2025-05-19,price_2025-05-20,price_2025-05-21,price_2025-05-22,price_2025-05-23,price_2025-05-24,price_2025-05-25,price_2025-05-26,price_2025-05-27,price_2025-05-28,price_2025-05-29,price_2025-05-30,price_2025-05-31,price_2025-06-01,price_2025-06-02,price_2025-06-03,price_2025-06-04,price_2025-06-05,price_2025-06-06,price_2025-06-07,price_2025-06-08,price_2025-06-09,price_2025-06-10,price_2025-06-11,price_2025-06-12,price_2025-06-13,price_2025-06-14,price_2025-06-15,price_2025-06-16,price_2025-06-17,price_2025-06-18,price_2025-06-19,price_2025-06-20,price_2025-06-21,price_2025-06-22,price_2025-06-23,price_2025-06-24,price_2025-06-25,price_2025-06-26,price_2025-06-27,price_2025-06-28,price_2025-06-29,price_2025-06-30,price_2025-07-01,price_2025-07-02,price_2025-07-03,price_2025-07-04,price_2025-07-05,price_2025-07-06,price_2025-07-07,price_2025-07-08,price_2025-07-09,price_2025-07-10,price_2025-07-11,price_2025-07-12,price_2025-07-13,price_2025-07-14,price_2025-07-15,price_2025-07-16,price_2025-07-17,price_2025-07-18,price_2025-07-19,price_2025-07-20,price_2025-07-21,price_2025-07-22,price_2025-07-23,price_2025-07-24,price_2025-07-25,price_2025-07-26,price_2025-07-27,price_2025-07-28,price_2025-07-29,price_2025-07-30,price_2025-07-31,price_2025-08-01,price_2025-08-02,price_2025-08-03,price_2025-08-04,price_2025-08-05,price_2025-08-06,price_2025-08-07,price_2025-08-08,price_2025-08-09,price_2025-08-10,price_2025-08-11,price_2025-08-12,price_2025-08-13,price_2025-08-14,price_2025-08-15,price_2025-08-16,price_2025-08-17,price_2025-08-18,price_2025-08-19,price_2025-08-20,price_2025-08-21,price_2025-08-22,price_2025-08-23,price_2025-08-24,price_2025-08-25,price_2025-08-26,price_2025-08-27,price_2025-08-28,price_2025-08-29,price_2025-08-30,price_2025-08-31,price_2025-09-01,price_2025-09-02,price_2025-09-03,price_2025-09-04,price_2025-09-05,price_2025-09-06,price_2025-09-07,price_2025-09-08,price_2025-09-09,price_2025-09-10,price_2025-09-11,price_2025-09-12,price_2025-09-13,price_2025-09-14,price_2025-09-15,price_2025-09-16,price_2025-09-17,price_2025-09-18,price_2025-09-19,price_2025-09-20,price_2025-09-21,price_2025-09-22,price_2025-09-23,price_2025-09-24,price_2025-09-25,price_2025-09-26,price_2025-09-27,price_2025-09-28,price_2025-09-29,price_2025-09-30,price_2025-10-01,price_2025-10-02,price_2025-10-03,price_2025-10-04,price_2025-10-05,price_2025-10-06,price_2025-10-07,price_2025-10-08,price_2025-10-09,price_2025-10-10,price_2025-10-11,price_2025-10-12,price_2025-10-13,price_2025-10-14,price_2025-10-15,price_2025-10-16,price_2025-10-17,price_2025-10-18,price_2025-10-19,price_2025-10-20,price_2025-10-21,price_2025-10-22,price_2025-10-23,price_2025-10-24,price_2025-10-25,price_2025-10-26,price_2025-10-27,price_2025-10-28,price_2025-10-29,price_2025-10-30,price_2025-10-31,price_2025-11-01,price_2025-11-02,price_2025-11-03,price_2025-11-04,price_2025-11-05,price_2025-11-06,price_2025-11-07,price_2025-11-08,price_2025-11-09,price_2025-11-10,price_2025-11-11,price_2025-11-12,price_2025-11-13,price_2025-11-14,price_2025-11-15,price_2025-11-16,price_2025-11-17,price_2025-11-18,price_2025-11-19,price_2025-11-20,price_2025-11-21,price_2025-11-22,price_2025-11-23,price_2025-11-24,price_2025-11-25,price_2025-11-26,price_2025-11-27,price_2025-11-28,price_2025-11-29,price_2025-11-30,price_2025-12-01,price_2025-12-02,price_2025-12-03,price_2025-12-04,price_2025-12-05,price_2025-12-06,price_2025-12-07,price_2025-12-08,price_2025-12-09,price_2025-12-10,price_2025-12-11,price_2025-12-12,price_2025-12-13,price_2025-12-14,price_2025-12-15,price_2025-12-16,price_2025-12-17,price_2025-12-18,price_2025-12-19,price_2025-12-20,price_2025-12-21,price_2025-12-22,price_2025-12-23,price_2025-12-24,price_2025-12-25,price_2025-12-26,price_2025-12-27,price_2025-12-28,price_2025-12-29,price_2025-12-30,price_2025-12-31,price_2026-01-01,price_2026-01-02,price_2026-01-03,price_2026-01-04,price_2026-01-05,price_2026-01-06,price_2026-01-07,price_2026-01-08,price_2026-01-09,price_2026-01-10,price_2026-01-11,price_2026-01-12,price_2026-01-13,price_2026-01-14,price_2026-01-15,price_2026-01-16,price_2026-01-17,price_2026-01-18,price_2026-01-19,price_2026-01-20,price_2026-01-21,price_2026-01-22,price_2026-01-23,price_2026-01-24,price_2026-01-25,price_2026-01-26,price_2026-01-27,price_2026-01-28,price_2026-01-29,price_2026-01-30,price_2026-01-31
count,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00,19922.00
mean,2979.21,1973.40,2010.81,2009.95,2027.12,2027.91,2011.72,2011.58,2008.29,2007.68,2010.63,2027.95,2025.74,2009.95,2007.03,2009.93,2010.40,2008.99,2028.02,2029.10,2006.67,2006.98,2010.89,2009.39,2006.75,2027.49,2031.01,2011.83,2009.38,2009.53,2008.85,2011.74,2028.08,2030.74,2012.26,2011.71,2009.20,2010.74,2011.54,2028.88,2028.00,2011.43,2010.72,2009.76,2011.85,2010.99,2026.44,2028.25,2008.97,2007.34,2010.09,2007.52,2009.37,2027.00,2029.06,2011.12,2009.31,2012.27,2006.80,2007.87,2027.56,2029.26,2011.69,2009.59,2010.14,2011.23,2009.14,2026.61,2028.10,2010.13,2009.53,2008.56,2008.43,2009.40,2025.52,2026.24,2012.85,2006.92,2010.08,2009.50,2009.31,2026.87,2025.22,2008.66,2008.43,2008.63,2006.60,2010.04,2027.42,2027.58,2007.86,2011.30,2009.05,2010.90,2009.28,2027.36,2030.71,2013.02,2009.68,2010.99,2011.88,2009.96,2027.22,2029.48,2010.38,2010.16,1805.33,1735.87,1734.19,1734.10,1732.86,1936.86,2007.09,2012.46,2012.15,2009.10,2028.69,2029.41,2009.81,2011.33,2011.45,2011.28,2008.25,2026.83,2026.57,2009.79,2011.31,2011.64,2009.62,2010.23,2025.83,2029.43,2008.49,2007.87,2007.94,2010.14,2008.20,2027.74,2027.53,2009.21,2010.14,2010.07,2009.72,2012.28,2026.64,2027.55,2010.19,2008.89,2011.66,2008.23,2008.29,1770.51,1558.34,1464.61,1453.06,1449.20,1450.93,1446.19,1450.08,1446.57,1633.92,1720.46,1932.00,2008.05,1782.20,1669.37,1665.45,1668.36,1667.40,1763.15,1765.14,1764.21,1767.93,1964.03,1727.24,1526.74,1414.35,1392.92,1390.99,1392.11,1389.21,1388.99,1627.25,1853.27,1979.69,2010.94,2027.56,2027.64,2010.20,2010.81,2011.75,2011.75,2011.75,2029.06,2028.73,2009.97,2010.13,2010.59,2009.73,2012.55,2027.74,2027.68,2011.30,2010.00,2010.01,2011.86,2007.70,2025.82,2025.53,2010.74,2008.17,2008.36,2011.18,1775.28,1601.25,1571.21,1627.33,1630.56,1860.22,1994.90,2007.10,2030.49,2028.14,2010.54,2008.45,2008.76,2009.24,2007.44,2026.95,2027.21,1817.21,1735.22,1735.89,1733.95,1731.27,1732.69,1942.68,1729.02,1666.15,1663.67,1662.07,1667.71,1895.47,1693.89,1636.23,1634.27,1633.34,1631.04,1633.74,1634.07,1866.06,1998.05,2006.32,2006.53,2008.26,2010.15,2026.74,2030.13,2012.94,2007.24,2009.22,2009.21,2011.35,2027.30,2027.63,2009.13,1773.49,1599.52,1572.08,1572.10,1568.65,1571.63,1570.75,1806.65,1981.39,2012.06,2013.89,2027.56
std,9009.64,7333.59,7278.80,7284.77,7303.31,7341.98,7302.61,7303.21,7282.92,7285.39,7287.32,7288.05,7324.42,7230.88,7281.26,7279.75,7287.33,7250.63,7336.02,7339.13,7188.06,7220.99,7281.55,7292.92,7205.09,7321.87,7358.57,7306.36,7227.92,7289.07,7269.83,7314.44,7277.70,7349.10,7298.44,7300.76,7285.11,7288.45,7290.07,7340.19,7340.49,7294.39,7310.91,7290.24,7283.41,7288.06,7316.57,7342.73,7237.40,7236.18,7261.85,7267.85,7283.69,7282.05,7345.09,7299.75,7290.68,7313.92,7267.91,7272.68,7333.98,7310.64,7291.88,7277.72,7297.96,7264.39,7254.12,7321.82,7331.84,7298.52,7295.54,7281.57,7248.05,7283.59,7290.74,7304.72,7288.02,7269.96,7298.39,7267.07,7284.21,7315.83,7323.59,7277.40,7276.18,7202.91,7259.46,7303.21,7326.88,7331.91,7233.67,7292.01,7232.37,7292.73,7261.53,7325.49,7296.50,7312.83,7294.93,7300.24,7309.96,7302.97,7331.74,7351.19,7301.68,7294.50,6700.04,6519.98,6649.80,6550.05,6639.10,7161.03,7245.50,7295.94,7284.11,7294.62,7347.02,7337.72,7138.41,7296.04,7307.97,7247.18,7271.48,7348.18,7331.12,7246.81,7291.20,7323.05,7280.47,7291.77,7341.35,7346.07,7287.51,7289.74,7280.67,7252.71,7294.58,7325.44,7349.08,7286.12,7247.28,7289.31,7281.28,7304.58,7295.48,7342.63,7283.18,7276.58,7291.15,7266.46,7283.78,6577.74,5988.97,5638.30,5728.00,5682.16,5731.74,5551.67,5736.30,5611.81,6263.62,6507.61,7144.63,7301.51,6620.07,6259.41,6359.56,6484.86,6353.39,6762.62,6635.51,6653.82,6712.58,7250.97,6544.62,5859.96,5381.94,5381.58,5356.09,5521.67,5397.18,5459.58,6156.40,6842.44,7197.77,7278.40,7331.74,7336.65,7294.37,7292.23,7269.08,7259.25,7309.39,7337.53,7349.09,7265.94,7238.59,7289.47,7231.05,7295.97,7334.12,7325.89,7300.27,7259.41,7242.08,7301.99,7253.02,7330.18,7326.55,7300.96,7262.75,7295.47,7304.31,6600.17,6034.37,6033.44,6216.57,6209.52,6894.43,7194.43,7223.17,7351.23,7332.89,7292.03,7288.80,7214.14,7282.44,7287.59,7322.15,7326.90,6711.80,6484.91,6635.99,6636.70,6580.99,6580.07,7198.61,6540.30,6276.11,6227.14,6241.88,6313.60,6986.04,6405.11,6174.72,6268.81,6253.47,6104.77,6175.32,6190.10,6878.26,7257.98,7226.26,7282.42,7260.00,7279.03,7330.25,7355.82,7279.91,7239.52,7266.24,7282.02,7292.48,7328.33,7329.11,7241.47,6540.21,6069.00,5940.85,6101.86,5938.16,6099.10,6041.87,6739.52,7225.65,7306.06,7304.51,7345.02
min,35.00,35.00,34.00,33.10,34.60,34.60,33.90,34.30,34.60,33.00,34.60,34.60,34.50,33.80,33.20,34.60,34.30,33.60,34.60,34.60,33.70,34.60,34.60,34.50,33.80,34.60,34.60,34.60,34.60,34.60,34.60,34.60,34.60,34.20,34.60,33.30,32.90,34.60,33.80,34.10,33.80,34.60,34.50,34.60,34.60,34.60,34.60,34.60,34.60,34.60,34.30,33.60,34.60,34.60,34.60,32.80,34.60,34.30,34.40,34.60,34.60,34.60,34.60,34.60,34.60,34.40,34.60,34.30,34.60,34.60,34.60,34.60,34.60,34.60,34.60,34.60,34.60,33.60,34.20,34.60,33.80,34.20,34.60,34.50,33.60,34.10,33.80,34.30,33.60,34.60,32.20,33.70,33.90,34.60,34.20,34.60,34.60,33.70,34.50,33.60,34.60,34.00,34.60,34.60,33.70,34.20,32.00,30.90,31.80,31.30,30.90,33.90,34.60,34.30,34.60,34.60,34.30,34.60,34.60,34.60,34.00,33.30,34.60,34.60,34.60,34.60,34.60,34.40,34.20,34.60,34.60,34.60,34.60,34.10,34.60,34.40,33.40,34.60,34.60,33.20,34.60,34.60,34.10,34.60,34.60,34.60,34.20,33.20,34.60,34.40,34.50,31.70,29.30,29.30,26.80,28.10,26.90,26.10,25.90,26.80,29.70,30.20,33.00,34.60,31.80,31.60,30.20,30.50,31.70,31.60,31.70,31.60,32.70,33.80,31.00,28.20,26.50,24.80,27.50,26.50,24.30,24.70,28.10,30.90,33.70,34.60,34.60,34.60,34.60,34.60,33.60,34.60,33.20,34.60,34.60,34.60,34.00,34.30,34.60,34.20,34.60,33.50,34.60,34.60,34.10,34.60,34.60,34.40,34.60,34.60,34.60,34.20,33.60,30.80,28.40,30.20,30.70,31.40,34.20,34.60,34.40,34.60,34.10,34.60,34.40,34.30,34.60,33.60,34.60,34.60,32.00,31.50,29.40,31.60,32.30,32.10,34.60,31.80,29.70,32.20,30.10,29.80,32.60,30.60,31.40,30.10,29.70,29.20,30.70,29.10,33.80,33.90,34.60,34.10,34.30,33.30,34.60,34.40,34.60,34.60,34.50,34.60,34.00,34.60,34.60,34.50,31.70,29.80,28.70,29.20,29.80,28.60,28.30,33.00,34.00,34.50,34.60,34.60
25%,666.00,350.00,387.00,387.00,389.00,390.00,387.00,387.00,387.00,386.00,387.00,390.00,390.00,387.00,387.00,387.00,387.00,387.00,390.00,390.00,386.00,387.00,386.00,386.00,386.00,390.00,390.00,388.00,387.00,387.00,387.00,387.00,390.00,391.00,386.00,386.00,387.00,387.00,386.00,390.00,390.00,388.00,387.00,388.00,387.00,387.00,391.00,389.00,386.00,387.00,386.00,387.00,387.00,390.00,389.25,387.00,386.00,387.00,386.00,387.00,391.00,390.00,387.00,386.00,387.00,386.00,387.00,390.00,391.00,386.00,387.00,387.00,386.00,387.00,390.00,390.00,387.00,386.00,386.00,387.00,386.00,390.00,390.00,386.00,387.00,386.00,387.00,386.00,390.00,391.00,387.00,387.00,387.00,386.00,387.00,391.00,390.00,386.00,386.00,387.00,387.00,387.00,391.00,390.00,387.00,386.00,329.00,304.00,303.00,302.00,304.00,358.00,386.25,387.00,387.00,387.00,390.00,391.00,387.00,386.00,387.00,387.00,386.00,389.00,390.00,387.00,387.00,386.00,388.00,386.00,391.00,390.00,387.00,387.00,386.00,386.00,386.00,390.00,390.00,387.00,387.00,387.00,387.00,387.00,391.00,390.00,386.00,387.00,387.00,387.00,386.00,323.00,268.00,253.00,251.00,250.00,250.00,251.00,251.00,250.00,289.00,302.00,357.00,386.00,325.00,291.00,290.00,289.00,288.25,311.00,311.00,312.00,310.00,364.00,305.00,261.00,247.00,245.00,244.00,245.00,245.00,244.00,306.00,360.00,383.00,386.00,391.00,390.00,386.00,386.00,386.00,387.00,386.00,390.00,390.00,386.00,386.00,387.00,387.00,386.00,390.00,391.00,387.00,388.00,387.00,387.00,386.00,390.00,390.00,386.00,386.00,386.00,386.00,324.00,276.00,269.00,281.00,282.00,340.00,385.00,387.00,390.00,390.00,386.00,387.00,387.00,387.00,387.00,390.00,390.00,332.00,305.00,304.00,303.00,303.00,303.00,360.00,305.00,289.00,288.00,289.00,290.00,348.00,298.00,283.00,281.00,283.00,282.00,281.00,282.00,341.00,384.25,386.00,386.00,387.00,386.00,391.00,390.00,387.00,386.00,387.00,386.00,386.00,390.00,390.00,386.00,324.00,276.00,269.25,269.00,269.00,268.00,269.00,332.00,382.00,386.00,386.00,391.00
50%,1040.00,550.00,596.00,596.50,601.00,603.00,596.00,596.00,595.00,596.00,596.00,602.00,602.00,597.00,596.00,598.00,596.00,596.00,602.00,603.00,596.00,596.00,595.00,594.00,596.00,603.00,603.00,597.00,598.00,594.00,596.00,598.00,603.00,602.00,596.00,596.00,597.00,596.00,597.00,603.00,603.00,595.00,597.00,597.00,596.00,598.00,600.00,602.00,597.00,597.00,598.00,597.00,596.00,602.00,601.00,595.00,595.50,598.00,596.00,595.00,602.00,604.00,597.00,596.00,598.00,597.00,596.00,602.00,604.00,597.00,596.00,596.00,595.00,596.00,602.00,603.00,596.00,598.00,596.00,597.00,596.00,602.00,603.00,595.00,596.00,597.00,596.00,597.00,604.00,602.00,595.00,596.00,596.00,597.00,595.00,602.00,602.00,595.00,598.00,597.00,596.00,596.50,602.00,602.50,597.50,596.00,515.00,482.00,479.00,479.00,480.00,563.00,595.00,598.00,597.00,597.00,600.00,601.00,598.00,596.00,596.00,596.00,596.00,603.00,601.00,598.00,598.00,598.00,597.00,597.00,601.00,603.00,596.00,596.00,597.00,596.00,596.00,604.00,604.00,596.00,595.00,595.00,595.00,595.00,601.00,602.00,597.00,597.00,595.00,595.00,596.00,505.00,426.00,396.00,395.00,395.00,396.00,393.00,394.00,395.00,454.00,477.00,561.00,594.00,506.00,461.00,458.00,459.00,459.00,491.00,491.00,492.00,491.00,573.00,483.00,415.00,385.00,382.00,380.00,380.00,381.00,380.00,476.00,559.00,592.00,596.00,602.00,603.00,596.00,595.00,595.50,597.00,597.00,602.00,603.50,597.00,595.00,596.00,597.00,597.00,604.00,601.00,598.00,597.00,595.50,597.00,596.00,604.00,603.00,596.00,597.00,596.00,597.00,506.00,439.00,431.00,447.00,447.00,534.00,593.00,597.00,602.00,601.00,596.00,597.00,597.00,597.00,597.00,603.00,602.00,519.00,483.00,481.00,481.00,479.00,478.50,563.00,481.00,458.50,458.00,459.00,458.00,545.00,469.00,449.00,449.00,447.00,449.00,449.00,447.00,534.00,592.00,595.00,597.00,595.00,596.00,603.00,603.00,598.00,596.00,597.00,597.00,597.00,602.00,602.00,596.00,505.00,439.00,428.00,428.00,429.00,429.50,428.00,516.50,588.00,596.00,596.00,603.00
75%,1999.00,999.00,1090.00,1090.00,1100.00,1100.00,1090.00,1090.00,1090.00,1090.00,1090.00,1090.00,1100.00,1090.00,1090.00,1090.00,1090.00,1090.00,1100.00,1100.00,1090.00,1090.00,1090.00,1090.00,1090.00,1090.00,1097.50,1090.00,1090.00,1090.00,1090.00,1090.00,1100.00,1100.00,1090.00,1090.00,1090.00,1090.00,1090.00,1090.00,1100.00,1090.00,1090.00,1090.00,1090.00,1090.00,1100.00,1090.00,1090.00,1090.00,1090.00,1090.00,1090.00,1097.50,1100.00,1090.00,1090.00,1080.00,1090.00,1090.00,1100.00,1100.00,1090.00,1090.00,1090.00,1090.00,1090.00,1090.00,1100.00,1090.00,1090.00,1090.00,1090.00,1090.00,1090.00,1100.00,1090.00,1090.00,1090.00,1090.00,1090.00,1100.00,1100.00,1090.00,1090.00,1090.00,1090.00,1090.00,1090.00,1090.00,1090.00,1090.00,1090.00,1090.00,1080.00,1090.00,1097.50,1090.00,1090.00,1090.00,1090.00,1090.00,1100.00,1100.00,1080.00,1090.00,946.00,899.00,899.00,900.00,898.75,1010.00,1090.00,1090.00,1090.00,1090.00,1090.00,1100.00,1090.00,1090.00,1090.00,1090.00,1090.00,1100.00,1100.00,1090.00,1090.00,1090.00,1090.00,1090.00,1090.00,1100.00,1090.00,1090.00,1090.00,1090.00,1090.00,1090.00,1097.50,1080.00,1090.00,1090.00,1090.00,1090.00,1100.00,1100.00,1090.00,1090.00,1090.00,1080.00,1090.00,928.00,806.00,759.00,753.00,755.00,752.00,752.00,751.00,754.00,849.00,889.00,1010.00,1090.00,932.00,864.00,863.00,864.75,861.00,912.00,913.00,914.00,917.00,1020.00,892.00,789.00,737.00,730.00,730.00,728.00,724.00,729.00,875.00,1020.00,1070.00,1080.00,1100.00,1100.00,1090.00,1090.00,1090.00,1090.00,1090.00,1100.00,1090.00,1090.00,1090.00,1090.00,1090.00,1090.00,1100.00,1100.00,1090.00,1090.00,1090.00,1090.00,1090.00,1100.00,1100.00,1090.00,1090.00,1090.00,1090.00,930.75,829.00,810.00,843.00,843.00,980.00,1080.00,1090.00,1100.00,1100.00,1090.00,1090.00,1090.00,1090.00,1090.00,1100.00,1100.00,951.00,901.00,899.00,899.00,901.00,898.00,1010.00,894.00,864.00,863.00,861.75,864.75,990.00,876.75,855.00,846.00,843.00,843.75,845.00,845.00,984.00,1080.00,1090.00,1090.00,1090.00,1090.00,1100.00,1100.00,1090.00,1090.00,1090.00,1090.00,1090.00,1100.00,1100.00,1090.00,930.00,829.00,811.00,807.00,810.00,809.00,812.00,956.00,1070.00,1090.00,1090.00,1100.00

In [38]:
# ====================================
# IDENTIFY TARGET VARIABLE
# ====================================
print("=" * 60)
print("TARGET VARIABLE ANALYSIS")
print("=" * 60)

# Target = discounted_price (what we want to predict)
TARGET = 'discounted_price'

print(f"🎯 Target Variable: {TARGET}")
print(f"\n📊 Target Statistics:")
print(df[TARGET].describe())

print(f"\n📊 Sample values:")
print(df[TARGET].head(10))

# Also check retail_price
print(f"\n📊 Retail Price Statistics:")
print(df['retail_price'].describe())

============================================================
TARGET VARIABLE ANALYSIS
============================================================
🎯 Target Variable: discounted_price

📊 Target Statistics:
count    19922.00
mean      1973.40
std       7333.59
min         35.00
25%        350.00
50%        550.00
75%        999.00
max     571230.00
Name: discounted_price, dtype: float64

📊 Sample values:
0     379.00
1   22646.00
2     499.00
3     267.00
4     210.00
5     430.00
6     479.00
7   22646.00
8     349.00
9     479.00
Name: discounted_price, dtype: float64

📊 Retail Price Statistics:
count    19922.00
mean      2979.21
std       9009.64
min         35.00
25%        666.00
50%       1040.00
75%       1999.00
max     571230.00
Name: retail_price, dtype: float64

In [39]:
# ====================================
# CHECK MISSING VALUES
# ====================================
print("=" * 60)
print("MISSING VALUES ANALYSIS")
print("=" * 60)

# Calculate missing values
missing = df.isnull().sum()
missing_pct = (missing / len(df)) * 100

# Create summary dataframe
missing_df = pd.DataFrame({
    'Column': missing.index,
    'Missing Count': missing.values,
    'Missing %': missing_pct.values,
    'Data Type': df.dtypes.values
})

# Sort by missing count
missing_df = missing_df.sort_values('Missing Count', ascending=False)

# Display
print(missing_df.to_string(index=False))

print(f"\n📊 Total Missing Values: {df.isnull().sum().sum():,}")
print(f"📊 Total Cells: {df.shape[0] * df.shape[1]:,}")

============================================================
MISSING VALUES ANALYSIS
============================================================
                 Column  Missing Count  Missing % Data Type
                  brand           5866      29.33    object
           retail_price             80       0.40   float64
       price_2026-01-31             80       0.40   float64
       price_2026-01-30             80       0.40   float64
       price_2026-01-14             80       0.40   float64
       price_2026-01-13             80       0.40   float64
       price_2026-01-12             80       0.40   float64
       price_2026-01-24             80       0.40   float64
       price_2025-05-16             80       0.40   float64
       price_2025-05-17             80       0.40   float64
       price_2025-05-18             80       0.40   float64
       price_2025-05-19             80       0.40   float64
       price_2025-12-30             80       0.40   float64
       price_2025-12-31             80       0.40   float64
       price_2026-01-01             80       0.40   float64
       price_2026-01-02             80       0.40   float64
       price_2026-01-03             80       0.40   float64
       price_2026-01-04             80       0.40   float64
       price_2026-01-05             80       0.40   float64
       price_2026-01-06             80       0.40   float64
       price_2026-01-07             80       0.40   float64
       price_2026-01-08             80       0.40   float64
       price_2026-01-10             80       0.40   float64
       price_2025-05-31             80       0.40   float64
       price_2025-06-01             80       0.40   float64
       price_2025-06-02             80       0.40   float64
       price_2025-06-03             80       0.40   float64
       price_2025-06-04             80       0.40   float64
       price_2025-05-04             80       0.40   float64
       price_2025-05-05             80       0.40   float64
       price_2025-05-06             80       0.40   float64
       price_2025-05-07             80       0.40   float64
       price_2025-05-08             80       0.40   float64
       price_2025-05-09             80       0.40   float64
       price_2025-05-10             80       0.40   float64
       price_2025-05-11             80       0.40   float64
       price_2025-05-12             80       0.40   float64
       price_2025-05-13             80       0.40   float64
       price_2025-05-14             80       0.40   float64
       price_2025-06-16             80       0.40   float64
       price_2025-06-17             80       0.40   float64
       price_2025-06-18             80       0.40   float64
       price_2025-06-19             80       0.40   float64
       price_2025-06-20             80       0.40   float64
       price_2025-05-20             80       0.40   float64
       price_2025-05-21             80       0.40   float64
       price_2025-05-22             80       0.40   float64
       price_2025-05-23             80       0.40   float64
       price_2025-05-24             80       0.40   float64
       price_2025-05-25             80       0.40   float64
       price_2025-05-26             80       0.40   float64
       price_2025-05-27             80       0.40   float64
       price_2025-05-28             80       0.40   float64
       price_2025-05-29             80       0.40   float64
       price_2025-05-30             80       0.40   float64
       price_2025-07-02             80       0.40   float64
       price_2025-07-03             80       0.40   float64
       price_2025-07-04             80       0.40   float64
       price_2025-07-05             80       0.40   float64
       price_2025-07-06             80       0.40   float64
       price_2025-06-05             80       0.40   float64
       price_2025-06-06             80       0.40   float64
       price_2025-06-07             80       0.40   float64
       price_2025-06-08             80       0.40   float64
       price_2025-06-09             80       0.40   float64
       price_2025-06-10             80       0.40   float64
       price_2025-06-11             80       0.40   float64
       price_2025-06-12             80       0.40   float64
       price_2025-06-13             80       0.40   float64
       price_2025-06-14             80       0.40   float64
       price_2025-06-15             80       0.40   float64
       price_2025-07-18             80       0.40   float64
       price_2025-07-19             80       0.40   float64
       price_2025-07-20             80       0.40   float64
       price_2025-07-21             80       0.40   float64
       price_2025-07-22             80       0.40   float64
       price_2025-06-21             80       0.40   float64
       price_2025-06-22             80       0.40   float64
       price_2025-06-23             80       0.40   float64
       price_2025-06-24             80       0.40   float64
       price_2025-06-25             80       0.40   float64
       price_2025-06-26             80       0.40   float64
       price_2025-06-27             80       0.40   float64
       price_2025-06-28             80       0.40   float64
       price_2025-06-29             80       0.40   float64
       price_2025-06-30             80       0.40   float64
       price_2025-07-01             80       0.40   float64
       price_2025-08-03             80       0.40   float64
       price_2025-08-04             80       0.40   float64
       price_2025-08-05             80       0.40   float64
       price_2025-08-06             80       0.40   float64
       price_2025-08-07             80       0.40   float64
       price_2025-07-07             80       0.40   float64
       price_2025-07-08             80       0.40   float64
       price_2025-07-09             80       0.40   float64
       price_2025-07-10             80       0.40   float64
       price_2025-07-11             80       0.40   float64
       price_2025-07-12             80       0.40   float64
       price_2025-07-13             80       0.40   float64
       price_2025-07-14             80       0.40   float64
       price_2025-07-15             80       0.40   float64
       price_2025-07-16             80       0.40   float64
       price_2025-07-17             80       0.40   float64
       price_2025-08-19             80       0.40   float64
       price_2025-08-20             80       0.40   float64
       price_2025-08-21             80       0.40   float64
       price_2025-08-22             80       0.40   float64
       price_2025-08-23             80       0.40   float64
       price_2025-07-23             80       0.40   float64
       price_2025-07-24             80       0.40   float64
       price_2025-07-25             80       0.40   float64
       price_2025-07-26             80       0.40   float64
       price_2025-07-27             80       0.40   float64
       price_2025-07-28             80       0.40   float64
       price_2025-07-29             80       0.40   float64
       price_2025-07-30             80       0.40   float64
       price_2025-07-31             80       0.40   float64
       price_2025-08-01             80       0.40   float64
       price_2025-08-02             80       0.40   float64
       price_2025-09-04             80       0.40   float64
       price_2025-09-05             80       0.40   float64
       price_2025-09-06             80       0.40   float64
       price_2025-09-07             80       0.40   float64
       price_2025-09-08             80       0.40   float64
       price_2025-08-08             80       0.40   float64
       price_2025-08-09             80       0.40   float64
       price_2025-08-10             80       0.40   float64
       price_2025-08-11             80       0.40   float64
       price_2025-08-12             80       0.40   float64
       price_2025-08-13             80       0.40   float64
       price_2025-08-14             80       0.40   float64
       price_2025-08-15             80       0.40   float64
       price_2025-08-16             80       0.40   float64
       price_2025-08-17             80       0.40   float64
       price_2025-08-18             80       0.40   float64
       price_2025-09-20             80       0.40   float64
       price_2025-09-21             80       0.40   float64
       price_2025-09-22             80       0.40   float64
       price_2025-09-23             80       0.40   float64
       price_2025-09-24             80       0.40   float64
       price_2025-08-24             80       0.40   float64
       price_2025-08-25             80       0.40   float64
       price_2025-08-26             80       0.40   float64
       price_2025-08-27             80       0.40   float64
       price_2025-08-28             80       0.40   float64
       price_2025-08-29             80       0.40   float64
       price_2025-08-30             80       0.40   float64
       price_2025-08-31             80       0.40   float64
       price_2025-09-01             80       0.40   float64
       price_2025-09-02             80       0.40   float64
       price_2025-09-03             80       0.40   float64
       price_2025-10-06             80       0.40   float64
       price_2025-10-07             80       0.40   float64
       price_2025-10-08             80       0.40   float64
       price_2025-10-09             80       0.40   float64
       price_2025-10-10             80       0.40   float64
       price_2025-09-09             80       0.40   float64
       price_2025-09-10             80       0.40   float64
       price_2025-09-11             80       0.40   float64
       price_2025-09-12             80       0.40   float64
       price_2025-09-13             80       0.40   float64
       price_2025-09-14             80       0.40   float64
       price_2025-09-15             80       0.40   float64
       price_2025-09-16             80       0.40   float64
       price_2025-09-17             80       0.40   float64
       price_2025-09-18             80       0.40   float64
       price_2025-09-19             80       0.40   float64
       price_2025-10-22             80       0.40   float64
       price_2025-10-23             80       0.40   float64
       price_2025-10-24             80       0.40   float64
       price_2025-10-25             80       0.40   float64
       price_2025-10-26             80       0.40   float64
       price_2025-09-25             80       0.40   float64
       price_2025-09-26             80       0.40   float64
       price_2025-09-27             80       0.40   float64
       price_2025-09-28             80       0.40   float64
       price_2025-09-29             80       0.40   float64
       price_2025-09-30             80       0.40   float64
       price_2025-10-01             80       0.40   float64
       price_2025-10-02             80       0.40   float64
       price_2025-10-03             80       0.40   float64
       price_2025-10-04             80       0.40   float64
       price_2025-10-05             80       0.40   float64
       price_2025-11-07             80       0.40   float64
       price_2025-11-08             80       0.40   float64
       price_2025-11-09             80       0.40   float64
       price_2025-11-10             80       0.40   float64
       price_2025-11-11             80       0.40   float64
       price_2025-10-11             80       0.40   float64
       price_2025-10-12             80       0.40   float64
       price_2025-10-13             80       0.40   float64
       price_2025-10-14             80       0.40   float64
       price_2025-10-15             80       0.40   float64
       price_2025-10-16             80       0.40   float64
       price_2025-10-17             80       0.40   float64
       price_2025-10-18             80       0.40   float64
       price_2025-10-19             80       0.40   float64
       price_2025-10-20             80       0.40   float64
       price_2025-10-21             80       0.40   float64
       price_2025-11-23             80       0.40   float64
       price_2025-11-24             80       0.40   float64
       price_2025-11-25             80       0.40   float64
       price_2025-11-26             80       0.40   float64
       price_2025-11-27             80       0.40   float64
       price_2025-10-27             80       0.40   float64
       price_2025-10-28             80       0.40   float64
       price_2025-10-29             80       0.40   float64
       price_2025-10-30             80       0.40   float64
       price_2025-10-31             80       0.40   float64
       price_2025-11-01             80       0.40   float64
       price_2025-11-02             80       0.40   float64
       price_2025-11-03             80       0.40   float64
       price_2025-11-04             80       0.40   float64
       price_2025-11-05             80       0.40   float64
       price_2025-11-06             80       0.40   float64
       price_2025-12-09             80       0.40   float64
       price_2025-12-10             80       0.40   float64
       price_2025-12-11             80       0.40   float64
       price_2025-12-12             80       0.40   float64
       price_2025-12-13             80       0.40   float64
       price_2025-11-12             80       0.40   float64
       price_2025-11-13             80       0.40   float64
       price_2025-11-14             80       0.40   float64
       price_2025-11-15             80       0.40   float64
       price_2025-11-16             80       0.40   float64
       price_2025-11-17             80       0.40   float64
       price_2025-11-18             80       0.40   float64
       price_2025-11-19             80       0.40   float64
       price_2025-11-20             80       0.40   float64
       price_2025-11-21             80       0.40   float64
       price_2025-11-22             80       0.40   float64
       price_2025-12-25             80       0.40   float64
       price_2025-12-26             80       0.40   float64
       price_2025-12-27             80       0.40   float64
       price_2025-12-28             80       0.40   float64
       price_2025-12-29             80       0.40   float64
       price_2025-11-28             80       0.40   float64
       price_2025-11-29             80       0.40   float64
       price_2025-11-30             80       0.40   float64
       price_2025-12-01             80       0.40   float64
       price_2025-12-02             80       0.40   float64
       price_2025-12-03             80       0.40   float64
       price_2025-12-04             80       0.40   float64
       price_2025-12-05             80       0.40   float64
       price_2025-12-06             80       0.40   float64
       price_2025-12-07             80       0.40   float64
       price_2025-12-08             80       0.40   float64
       price_2026-01-11             80       0.40   float64
       price_2026-01-26             80       0.40   float64
       price_2026-01-27             80       0.40   float64
       price_2026-01-28             80       0.40   float64
       price_2026-01-29             80       0.40   float64
       price_2025-12-14             80       0.40   float64
       price_2025-12-15             80       0.40   float64
       price_2025-12-16             80       0.40   float64
       price_2025-12-17             80       0.40   float64
       price_2025-12-18             80       0.40   float64
       price_2025-12-19             80       0.40   float64
       price_2025-12-20             80       0.40   float64
       price_2025-12-21             80       0.40   float64
       price_2025-12-22             80       0.40   float64
       price_2025-12-23             80       0.40   float64
       price_2025-05-15             80       0.40   float64
       price_2025-12-24             80       0.40   float64
       discounted_price             80       0.40   float64
       price_2026-01-09             80       0.40   float64
       price_2025-05-01             80       0.40   float64
       price_2025-05-02             80       0.40   float64
       price_2025-05-03             80       0.40   float64
       price_2026-01-15             80       0.40   float64
       price_2026-01-16             80       0.40   float64
       price_2026-01-17             80       0.40   float64
       price_2026-01-18             80       0.40   float64
       price_2026-01-19             80       0.40   float64
       price_2026-01-20             80       0.40   float64
       price_2026-01-21             80       0.40   float64
       price_2026-01-22             80       0.40   float64
       price_2026-01-23             80       0.40   float64
       price_2026-01-25             80       0.40   float64
 product_specifications             16       0.08    object
                  image              5       0.02    object
            description              4       0.02    object
            product_url              2       0.01    object
                    pid              2       0.01    object
  product_category_tree              2       0.01    object
           product_name              2       0.01    object
is_FK_Advantage_product              2       0.01    object
         product_rating              2       0.01    object
         overall_rating              2       0.01    object
        crawl_timestamp              2       0.01    object
                uniq_id              2       0.01    object

📊 Total Missing Values: 28,149
📊 Total Cells: 5,820,582

In [40]:
# Remove these 3 columns
df.drop(columns=['is_FK_Advantage_product', 'product_rating', 'overall_rating'], inplace=True)

In [41]:
# Remove ALL rows that have ANY missing value
df.dropna(inplace=True)

In [42]:
# ====================================
# METHOD 2: FILL WITH MEDIAN (RECOMMENDED FOR PRICE)
# ====================================
print("=" * 70)
print("FILLING NUMERICAL COLUMNS WITH MEDIAN")
print("=" * 70)

# Reload data if you want to try median instead
# df = pd.read_csv('../data/raw/product_data.csv')

# List of numerical columns to fill with median
numerical_cols_to_fill = ['retail_price', 'discounted_price', 'product_rating', 'overall_rating']

for col in numerical_cols_to_fill:
    if col in df.columns:
        missing_before = df[col].isnull().sum()
        
        if missing_before > 0:
            # Calculate median
            median_value = df[col].median()
            
            # Fill missing values

======================================================================
FILLING NUMERICAL COLUMNS WITH MEDIAN
======================================================================

In [43]:
# ====================================
# VISUALIZE MISSING VALUES
# ====================================
plt.figure(figsize=(12, 6))

# Plot missing values
missing_data = df.isnull().sum()
missing_data = missing_data[missing_data > 0].sort_values(ascending=False)

if len(missing_data) > 0:
    plt.barh(missing_data.index, missing_data.values, color='coral')
    plt.xlabel('Missing Count')
    plt.ylabel('Columns')
    plt.title('Missing Values by Column')
    
    # Add percentage labels
    for i, v in enumerate(missing_data.values):
        pct = (v / len(df)) * 100
        plt.text(v + 50, i, f'{pct:.1f}%', va='center')
    
    plt.tight_layout()
    plt.show()
else:
    print("✅ No missing values to visualize!")

✅ No missing values to visualize!

In [44]:
# ====================================
# CHECK DUPLICATE ROWS
# ====================================
print("=" * 60)
print("DUPLICATE ANALYSIS")
print("=" * 60)

# Check complete duplicates
duplicates = df.duplicated().sum()
print(f"📊 Complete Duplicate Rows: {duplicates:,}")
print(f"📊 Percentage: {(duplicates/len(df))*100:.2f}%")

# Check duplicates by specific columns
print(f"\n📊 Duplicates by uniq_id: {df['uniq_id'].duplicated().sum():,}")

if 'pid' in df.columns:
    print(f"📊 Duplicates by pid: {df['pid'].duplicated().sum():,}")

============================================================
DUPLICATE ANALYSIS
============================================================
📊 Complete Duplicate Rows: 0
📊 Percentage: 0.00%

📊 Duplicates by uniq_id: 0
📊 Duplicates by pid: 2

In [45]:
# ====================================
# CHECK RATING COLUMNS (Mostly Empty)
# ====================================
print("=" * 60)
print("RATING COLUMNS ANALYSIS")
print("=" * 60)

# Product Rating
if 'product_rating' in df.columns:
    print("\n📊 PRODUCT RATING:")
    print(f"   Total rows: {len(df):,}")
    print(f"   Missing: {df['product_rating'].isnull().sum():,}")
    print(f"   Missing %: {(df['product_rating'].isnull().sum()/len(df))*100:.1f}%")
    print(f"   Non-null values: {df['product_rating'].notna().sum():,}")

# Overall Rating
if 'overall_rating' in df.columns:
    print("\n📊 OVERALL RATING:")
    print(f"   Total rows: {len(df):,}")
    print(f"   Missing: {df['overall_rating'].isnull().sum():,}")
    print(f"   Missing %: {(df['overall_rating'].isnull().sum()/len(df))*100:.1f}%")
    print(f"   Non-null values: {df['overall_rating'].notna().sum():,}")

print("\n⚠️ Note: Rating columns are mostly empty - will handle in cleaning!")

============================================================
RATING COLUMNS ANALYSIS
============================================================

⚠️ Note: Rating columns are mostly empty - will handle in cleaning!

In [46]:
# ====================================
# CHECK PRICE COLUMNS
# ====================================
print("=" * 60)
print("PRICE COLUMNS ANALYSIS")
print("=" * 60)

price_cols = ['retail_price', 'discounted_price']

for col in price_cols:
    if col in df.columns:
        print(f"\n📊 {col.upper()}:")
        print(f"   Data Type: {df[col].dtype}")
        print(f"   Missing: {df[col].isnull().sum():,}")
        print(f"   Sample values: {df[col].head(5).tolist()}")

============================================================
PRICE COLUMNS ANALYSIS
============================================================

📊 RETAIL_PRICE:
   Data Type: float64
   Missing: 0
   Sample values: [999.0, 32157.0, 999.0, 699.0, 220.0]

📊 DISCOUNTED_PRICE:
   Data Type: float64
   Missing: 0
   Sample values: [379.0, 22646.0, 499.0, 267.0, 210.0]

In [47]:
# ====================================
# CHECK BRAND COLUMN
# ====================================
print("=" * 60)
print("BRAND COLUMN ANALYSIS")
print("=" * 60)

if 'brand' in df.columns:
    print(f"📊 Unique Brands: {df['brand'].nunique():,}")
    print(f"📊 Missing: {df['brand'].isnull().sum():,}")
    print(f"\n📊 Top 10 Brands:")
    print(df['brand'].value_counts().head(10))

============================================================
BRAND COLUMN ANALYSIS
============================================================
📊 Unique Brands: 3,481
📊 Missing: 0

📊 Top 10 Brands:
brand
Allure Auto     468
Regular         308
Voylla          299
Slim            284
TheLostPuppy    229
Karatcraft      211
Black           167
White           155
DailyObjects    144
Speedwav        141
Name: count, dtype: int64

In [48]:
# ====================================
# CHECK PRODUCT CATEGORY TREE
# ====================================
print("=" * 60)
print("PRODUCT CATEGORY TREE ANALYSIS")
print("=" * 60)

if 'product_category_tree' in df.columns:
    print(f"📊 Unique Categories: {df['product_category_tree'].nunique():,}")
    print(f"📊 Missing: {df['product_category_tree'].isnull().sum():,}")
    print(f"\n📊 Sample Category Tree:")
    print(df['product_category_tree'].head(3).tolist())

============================================================
PRODUCT CATEGORY TREE ANALYSIS
============================================================
📊 Unique Categories: 4,768
📊 Missing: 0

📊 Sample Category Tree:
['["Clothing >> Women\'s Clothing >> Lingerie, Sleep & Swimwear >> Shorts >> Alisha Shorts >> Alisha Solid Women\'s Cycling Shorts"]', '["Furniture >> Living Room Furniture >> Sofa Beds & Futons >> FabHomeDecor Fabric Double Sofa Bed (Finish Colo..."]', '["Footwear >> Women\'s Footwear >> Ballerinas >> AW Bellies"]']

In [49]:
# ====================================
# DATA SUMMARY
# ====================================
print("=" * 60)
print("📋 NOTEBOOK 01 - DATA SUMMARY")
print("=" * 60)

print(f"""
📊 Dataset Shape: {df.shape[0]:,} rows × {df.shape[1]} columns

📊 Column Categories:
   • ID Columns: uniq_id, pid
   • Price Columns: retail_price, discounted_price
   • Text Columns: product_name, description, product_url, images
   • Category: product_category_tree, brand
   • Rating: product_rating, overall_rating (⚠️ mostly empty)
   • Other: crawl_timestamp, product_specifications

📊 Target Variable: discounted_price

📊 Missing Values: {df.isnull().sum().sum():,} total

📊 Duplicates: {df.duplicated().sum():,} rows

⚠️ Issues Found:
   • Rating columns are mostly empty
   • Price columns may have currency symbols
   • Category tree needs extraction
""")

============================================================
📋 NOTEBOOK 01 - DATA SUMMARY
============================================================

📊 Dataset Shape: 14,058 rows × 288 columns

📊 Column Categories:
   • ID Columns: uniq_id, pid
   • Price Columns: retail_price, discounted_price
   • Text Columns: product_name, description, product_url, images
   • Category: product_category_tree, brand
   • Rating: product_rating, overall_rating (⚠️ mostly empty)
   • Other: crawl_timestamp, product_specifications

📊 Target Variable: discounted_price

📊 Missing Values: 0 total

📊 Duplicates: 0 rows

⚠️ Issues Found:
   • Rating columns are mostly empty
   • Price columns may have currency symbols
   • Category tree needs extraction

In [50]:
df1 = df.isnull()

In [52]:
# ====================================
# SAVE RAW SNAPSHOT
# ====================================

# Create directory if not exists
os.makedirs('D:\ML_project', exist_ok=True)

# Save snapshot
df.to_csv('D:\ML_project/01_raw_snapshot.csv', index=False)

print("=" * 60)
print("✅ RAW SNAPSHOT SAVED!")
print("=" * 60)
print(f"📁 Location: data/processed/01_raw_snapshot.csv")
print(f"📊 Rows: {df.shape[0]:,}")
print(f"📊 Columns: {df.shape[1]}")
print("\n➡️ Proceed to Notebook 02: Data Cleaning")

============================================================
✅ RAW SNAPSHOT SAVED!
============================================================
📁 Location: data/processed/01_raw_snapshot.csv
📊 Rows: 14,058
📊 Columns: 288

➡️ Proceed to Notebook 02: Data Cleaning